### ISSUE TITLE
practica 6

### ISSUE THREAD

**Issue by 22620229Angel** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo-osteas-b#1]
[Practica #6 (2).pdf](https://github.com/user-attachments/files/17156486/Practica.6.2.pdf)

**Comment by williamgl3** [comment]
cumple con todas las rubricas de la practica 20/20 bien echo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
